"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Answer:  4613732
"""
# x,y = 1, 2
# fibo = []
# for i in range(50):
#     temp = 0
#     temp = temp + x
#     if temp % 2 == 0 and temp <= 4000000:
#         fibo.append(temp)
#     x, y = y, x+y
# print(sum(fibo))

x,y = 1,2
fibo = []
n = 0
while n <= 10:
    temp = 0
    temp = temp + x
    fibo.append(temp)
    x, y = y, x+y
    n = n + 1
print(fibo)
